# Generated by Django 5.1.3 on 2024-12-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.CharField(choices=[('АСМБ София', 'АСМБ София'), ('АСМБ СУ', 'АСМБ СУ'), ('АСМБ Варна', 'АСМБ Варна'), ('АСМ Пловдив', 'АСМ Пловдив'), ('АСМБ Бургас', 'АСМБ Бургас'), ('АСМБ Плевен', 'АСМБ Плевен'), ('АСМБ Стара Загора', 'АСМБ Стара Загора')], default='АСМБ СУ', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('Local', 'Local'), ('National', 'National')], default='Local', max_length=100),
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField(default=0)),
                ('organizers', models.TextField(blank=True, max_length=100, null=True)),
                ('prepared', models.TextField(blank=True, max_length=35, null=True)),
                ('attended', models.TextField(blank=True, max_length=1000, null=True)),
                ('participated_actively', models.TextField(blank=True, max_length=350, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('points_for_organizers', models.IntegerField(default=0)),
                ('points_for_prepared', models.IntegerField(default=0)),
                ('points_for_attended', models.IntegerField(default=0)),
                ('points_for_participated_actively', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event')),
            ],
        ),
    ]
