# Generated by Django 5.1.3 on 2024-12-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_approve_events', 'Can approve event'), ('can_make_report', 'Can make report')]},
        ),
    ]
