# Generated by Django 5.1.3 on 2024-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='name',
            field=models.CharField(default='Student meeting', max_length=150),
        ),
    ]
