# Generated by Django 5.1.3 on 2024-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='asmbtest@test.bg', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
