# Generated by Django 5.1.3 on 2024-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstudent',
            name='can_make_reports',
            field=models.BooleanField(default=False),
        ),
    ]
