# Generated by Django 5.1.3 on 2024-12-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appstudent_can_make_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
