# Generated by Django 5.1.3 on 2024-12-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_activity_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_information',
        ),
    ]
