# Generated by Django 5.1.3 on 2024-11-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstudent',
            name='points',
        ),
        migrations.AddField(
            model_name='customstudent',
            name='branch',
            field=models.CharField(choices=[('АСМБ МУ', 'АСМБ МУ'), ('АСМБ СУ', 'АСМБ СУ'), ('АСМБ Варна', 'АСМБ Варна'), ('АСМБ Пловдив', 'АСМБ Пловдив'), ('АСМБ Бургас', 'АСМБ Бургас'), ('АСМБ Плевен', 'АСМБ Плевен'), ('АСМБ Стара Загора', 'АСМБ Стара Загора')], default='АСМБ СУ', max_length=25),
        ),
        migrations.AddField(
            model_name='customstudent',
            name='faculty_number',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
    ]
