# Generated by Django 5.1.3 on 2024-12-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstudent',
            name='branch',
            field=models.CharField(choices=[('АСМБ София', 'АСМБ София'), ('АСМБ СУ', 'АСМБ СУ'), ('АСМБ Варна', 'АСМБ Варна'), ('АСМ Пловдив', 'АСМ Пловдив'), ('АСМБ Бургас', 'АСМБ Бургас'), ('АСМБ Плевен', 'АСМБ Плевен'), ('АСМБ Стара Загора', 'АСМБ Стара Загора')], default='АСМБ СУ', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('АСМБ София', 'АСМБ София'), ('АСМБ СУ', 'АСМБ СУ'), ('АСМБ Варна', 'АСМБ Варна'), ('АСМ Пловдив', 'АСМ Пловдив'), ('АСМБ Бургас', 'АСМБ Бургас'), ('АСМБ Плевен', 'АСМБ Плевен'), ('АСМБ Стара Загора', 'АСМБ Стара Загора')], default='АСМБ СУ', max_length=25),
        ),
    ]
