# Generated by Django 5.1.3 on 2024-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaing_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='points_for_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaing',
            name='points_for_organizers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaing',
            name='points_for_participated_in_preliminary_training',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaing',
            name='points_for_prepared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaing',
            name='points_for_presented',
            field=models.IntegerField(default=0),
        ),
    ]
